//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestESSILOR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public int Author_id { get; set; }
        public string First_name { get; set; }
        public string familt_name { get; set; }
        public Nullable<System.DateTime> date0fbirth { get; set; }
        public Nullable<System.DateTime> date0fdeath { get; set; }
        public string name { get; set; }
        public string lifespan { get; set; }
        public string URL { get; set; }
    }
}
