//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestESSILOR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookId { get; set; }
        public string title { get; set; }
        public string Author { get; set; }
        public string summary { get; set; }
        public string ISBN { get; set; }
        public string genre { get; set; }
        public string URL { get; set; }
    }
}
